

<template>
  <div class="relative bg-gradient-to-b from-blue-400 to-blue-100 p-8 flex flex-col items-center rounded-lg drop-shadow-lg">
    <div>
      <p class="text-center text-xl font-bold">Il Libro di Mormon</p>
      <p class="text-center text-md font-semibold mb-2">Ad alta voce</p>
    </div>
    <img
      class="rounded-full h-40 w-40"
      :src="currentImage"
      alt="narratorImageName no image"
    />
    <div class="flex flex-col items-center mx-2 text-lg text-black font-bold">
      {{ selectedReader.narrator }}
    </div>
    <div class="flex flex-col items-center text-black text-base font-semibold">
      {{ selectedReader.book }}
      {{ selectedReader.chapter }}
    </div>
    <div class="container">
      <div class="flex justify-around mt-0 items-center mb-2">
        <button
          type="button"
          class="transition w-4 h-4 mt-4 fill-current hover:fill-blue-600"
          @click="prev"
        >
          <icon name="prev"></icon>
        </button>
        <button
          type="button"
          class="transition w-4 h-4 mt-4 fill-current hover:fill-blue-600"
          @click="play"
          v-if="!isPlaying"
        >
          <icon name="play"></icon>
        </button>
        <button
          type="button"
          class="transition w-4 h-4 mt-4 fill-current hover:fill-blue-600"
          @click="pause"
          v-else
        >
          <icon name="pause"></icon>
        </button>
        <button
          type="button"
          class="transition w-4 h-4 mt-4 fill-current hover:fill-blue-600"
          @click="next"
        >
          <icon name="next"></icon>
        </button>
      </div>
      <div class="container mt-2 w-full">
        <div
          class="
            relative
            container
            flex flex-col
            objects-center
            mt-2
          "
        >
          <div class="flex flex-1 flex-col items-center space-x-1 mt-4">
            <input
              type="range"
              max="100"
              id="progressBar"
              v-model="audio.currentTime"
              class="cursor-pointer"
            />
            <div class="flex justify-between font-semibold">
              <span>{{ currentTimeTxt }} / {{ currentDurationTxt }}</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { useReaderStore } from "../stores/Readers";
import Tab2 from "./Tab2.vue";
import { ref } from "vue";
import axios from "axios";
import { Inertia } from "@inertiajs/inertia";
import { computed } from "vue";
import { usePage } from "@inertiajs/inertia-vue3";

export default {
  props: ["newReader"],
  data() {
    return {
      audio: new Audio(),
      isPlaying: false,
      currentReader: {}, //this will be related to the User
      currentNarrator: "",
      currentImage: "",
      progressBar: {},
      currentDuration: 0,
      currentTime: 0,
      currentTimeTxt: "0:00",
      currentDurationTxt: "0:00",
      index: 5, //1 Nefi 1
      volume: 80,
      isMuted: false,
      isMaxed: false,
      pictureHasChanged: false,
      selectedReader: useReaderStore(),

      readers: [
        {
          uuid: 1,
          bookID: 1,
          book: "Intro",
          chapter: 1,
          narrator: "Tommaso Cardullo",
          narratorImageName: "TommasoCardullo",
          chapterImageName: "Intro1",
          audioFileName: "Intro1",
          isActiveBookmark: false,
          src: "assets/media/Intro1.mp3",
        },
        {
          uuid: 2,
          bookID: 1,
          book: "Intro",
          chapter: 2,
          narrator: "Vincenzo Conforte",
          narratorImageName: "VincenzoConforte",
          chapterImageName: "Intro2",
          audioFileName: "Intro2",
          isActiveBookmark: false,
          src: "assets/media/Intro2.mp3",
        },
        {
          uuid: 3,
          bookID: 1,
          book: "Intro",
          chapter: 3,
          narrator: "Carolina Conforte",
          narratorImageName: "CarolinaConforte",
          chapterImageName: "Intro3",
          audioFileName: "Intro3",
          isActiveBookmark: false,
          src: "assets/media/Intro3.mp3",
        },
        {
          uuid: 4,
          bookID: 1,
          book: "Intro",
          chapter: 4,
          narrator: "Carolina Conforte",
          narratorImageName: "CarolinaConforte",
          chapterImageName: "Intro4",
          audioFileName: "Intro4",
          isActiveBookmark: false,
          src: "assets/media/Intro4.mp3",
        },
        {
          uuid: 5,
          bookID: 1,
          book: "Intro",
          chapter: 5,
          narrator: "Noemi Tonon",
          narratorImageName: "NoemiTonon",
          chapterImageName: "Intro5",
          audioFileName: "Intro5",
          isActiveBookmark: false,
          src: "assets/media/Intro5.mp3",
        },
        {
          uuid: 6,
          bookID: 2,
          book: "1 Nefi",
          chapter: 1,
          narrator: "Giacomo Armillei",
          narratorImageName: "GiacomoArmillei",
          chapterImageName: "1Nephi1",
          audioFileName: "1Nefi1",
          isActiveBookmark: false,
          src: "assets/media/1Nefi1.mp3",
        },
        {
          uuid: 7,
          bookID: 2,
          book: "1 Nefi",
          chapter: 2,
          narrator: "Emanuele Cascone",
          narratorImageName: "EmanueleCascone",
          chapterImageName: "1Nephi2",
          audioFileName: "1Nefi2",
          isActiveBookmark: false,
          src: "assets/media/1Nefi2.mp3",
        },
        {
          uuid: 8,
          bookID: 2,
          book: "1 Nefi",
          chapter: 3,
          narrator: "Francesca Spatola",
          narratorImageName: "FrancescaSpatola",
          chapterImageName: "1Nephi3",
          audioFileName: "1Nefi3",
          isActiveBookmark: false,
          src: "assets/media/1Nefi3.mp3",
        },
        {
          uuid: 9,
          bookID: 2,
          book: "1 Nefi",
          chapter: 4,
          narrator: "Giancarlo Giorgino",
          narratorImageName: "GiancarloGiorgino",
          chapterImageName: "1Nephi4",
          audioFileName: "1Nefi4",
          isActiveBookmark: false,
          src: "assets/media/1Nefi4.mp3",
        },
        {
          uuid: 10,
          bookID: 2,
          book: "1 Nefi",
          chapter: 5,
          narrator: "Daniele Menis",
          narratorImageName: "DanieleMenis",
          chapterImageName: "1Nephi5",
          audioFileName: "1Nefi5",
          isActiveBookmark: false,
          src: "assets/media/1Nefi5.mp3",
        },
        {
          uuid: 11,
          bookID: 2,
          book: "1 Nefi",
          chapter: 6,
          narrator: "Enrico Greico",
          narratorImageName: "EnricoGreico",
          chapterImageName: "BOMpic",
          audioFileName: "1Nefi6",
          isActiveBookmark: false,
          src: "assets/media/1Nefi6.mp3",
        },
        {
          uuid: 12,
          bookID: 2,
          book: "1 Nefi",
          chapter: 7,
          narrator: "Camilla Botta",
          narratorImageName: "CamillaBotta",
          chapterImageName: "BOMpic",
          audioFileName: "1Nefi7",
          isActiveBookmark: false,
          src: "assets/media/1Nefi7.mp3",
        },
        {
          uuid: 13,
          bookID: 2,
          book: "1 Nefi",
          chapter: 8,
          narrator: "Cristina Perricone",
          narratorImageName: "CristinaPerricone",
          chapterImageName: "1Nephi8",
          audioFileName: "1Nefi8",
          isActiveBookmark: false,
          src: "assets/media/1Nefi8.mp3",
        },
        {
          uuid: 14,
          bookID: 2,
          book: "1 Nefi",
          chapter: 9,
          narrator: "Giorgio Cascone",
          narratorImageName: "GiorgioCascone",
          chapterImageName: "BOMpic",
          audioFileName: "1Nefi9",
          isActiveBookmark: false,
          src: "assets/media/1Nefi9.mp3",
        },
        {
          uuid: 15,
          bookID: 2,
          book: "1 Nefi",
          chapter: 10,
          narrator: "Giuseppe Armenise",
          narratorImageName: "GiuseppeArmenise",
          chapterImageName: "BOMpic",
          audioFileName: "1Nefi10",
          isActiveBookmark: false,
          src: "assets/media/1Nefi10.mp3",
        },
        {
          uuid: 16,
          bookID: 2,
          book: "1 Nefi",
          chapter: 11,
          narrator: "Alberto Malara",
          narratorImageName: "AlbertoMalara",
          chapterImageName: "1Nephi11",
          audioFileName: "1Nefi11",
          isActiveBookmark: false,
          src: "assets/media/1Nefi11.mp3",
        },
        {
          uuid: 17,
          bookID: 2,
          book: "1 Nefi",
          chapter: 12,
          narrator: "Maximiliano Virzo",
          narratorImageName: "MaximilianoVirzo",
          chapterImageName: "BOMpic",
          audioFileName: "1Nefi12",
          isActiveBookmark: false,
          src: "assets/media/1Nefi12.mp3",
        },
        {
          uuid: 18,
          bookID: 2,
          book: "1 Nefi",
          chapter: 13,
          narrator: "Maria Chiara Murgia",
          narratorImageName: "MariaMurgia",
          chapterImageName: "1Nephi13",
          audioFileName: "1Nefi13",
          isActiveBookmark: false,
          src: "assets/media/1Nefi13.mp3",
        },
        {
          uuid: 19,
          bookID: 2,
          book: "1 Nefi",
          chapter: 14,
          narrator: "Alessio Giolitto",
          narratorImageName: "AlessioGiolitto",
          chapterImageName: "BOMpic",
          audioFileName: "1Nefi14",
          isActiveBookmark: false,
          src: "assets/media/1Nefi14.mp3",
        },
        {
          uuid: 20,
          bookID: 2,
          book: "1 Nefi",
          chapter: 15,
          narrator: "Silvana Pulvirenti",
          narratorImageName: "SilvanaPulvirenti",
          chapterImageName: "BOMpic",
          audioFileName: "1Nefi15",
          isActiveBookmark: false,
          src: "assets/media/1Nefi15.mp3",
        },
        {
          uuid: 21,
          bookID: 2,
          book: "1 Nefi",
          chapter: 16,
          narrator: "Giunia Bressan",
          narratorImageName: "GiuniaBressan",
          chapterImageName: "1Nephi16",
          audioFileName: "1Nefi16",
          isActiveBookmark: false,
          src: "assets/media/1Nefi16.mp3",
        },
        {
          uuid: 22,
          bookID: 2,
          book: "1 Nefi",
          chapter: 17,
          narrator: "Eleonora Caravella",
          narratorImageName: "EleonoraCaravella",
          chapterImageName: "1Nephi17",
          audioFileName: "1Nefi17",
          isActiveBookmark: false,
          src: "assets/media/1Nefi17.mp3",
        },
        {
          uuid: 23,
          bookID: 2,
          book: "1 Nefi",
          chapter: 18,
          narrator: "Teresa Saieva",
          narratorImageName: "TeresaSaieva",
          chapterImageName: "1Nephi18",
          audioFileName: "1Nefi18",
          isActiveBookmark: false,
          src: "assets/media/1Nefi18.mp3",
        },
        {
          uuid: 24,
          bookID: 2,
          book: "1 Nefi",
          chapter: 19,
          narrator: "Eveline Gibilisco",
          narratorImageName: "EvelineGibilisco",
          chapterImageName: "1Nephi19",
          audioFileName: "1Nefi19",
          isActiveBookmark: false,
          src: "assets/media/1Nefi19.mp3",
        },
        {
          uuid: 25,
          bookID: 2,
          book: "1 Nefi",
          chapter: 20,
          narrator: "Marianna Pastano",
          narratorImageName: "MariannaPastano",
          chapterImageName: "1Nephi20",
          audioFileName: "1Nefi20",
          isActiveBookmark: false,
          src: "assets/media/1Nefi20.mp3",
        },
        {
          uuid: 26,
          bookID: 2,
          book: "1 Nefi",
          chapter: 21,
          narrator: "Rosi Zombra",
          narratorImageName: "RosiZombra",
          chapterImageName: "BOMpic",
          audioFileName: "1Nefi21",
          isActiveBookmark: false,
          src: "assets/media/1Nefi21.mp3",
        },
        {
          uuid: 27,
          bookID: 2,
          book: "1 Nefi",
          chapter: 22,
          narrator: "Emily Cascone",
          narratorImageName: "EmilyCascone",
          chapterImageName: "BOMpic",
          audioFileName: "1Nefi22",
          isActiveBookmark: false,
          src: "assets/media/1Nefi22.mp3",
        },
        {
          uuid: 28,
          bookID: 3,
          book: "2 Nefi",
          chapter: 1,
          narrator: "Naomi Caraffa",
          narratorImageName: "NaomiCaraffa",
          chapterImageName: "2Nephi1",
          audioFileName: "2Nefi1",
          isActiveBookmark: false,
          src: "assets/media/2Nefi1.mp3",
        },
        {
          uuid: 29,
          bookID: 3,
          book: "2 Nefi",
          chapter: 2,
          narrator: "Francesca Spatola",
          narratorImageName: "FrancescaSpatola",
          chapterImageName: "2Nephi2",
          audioFileName: "2Nefi2",
          isActiveBookmark: false,
          src: "assets/media/2Nefi2.mp3",
        },
        {
          uuid: 30,
          bookID: 3,
          book: "2 Nefi",
          chapter: 3,
          narrator: "Florinda Ferreri",
          narratorImageName: "FlorindaFerreri",
          chapterImageName: "2Nephi3",
          audioFileName: "2Nefi3",
          isActiveBookmark: false,
          src: "assets/media/2Nefi3.mp3",
        },
        {
          uuid: 31,
          bookID: 3,
          book: "2 Nefi",
          chapter: 4,
          narrator: "Andrea Santoro",
          narratorImageName: "AndreaSantoro",
          chapterImageName: "2Nephi4",
          audioFileName: "2Nefi4",
          isActiveBookmark: false,
          src: "assets/media/2Nefi4.mp3",
        },
        {
          uuid: 32,
          bookID: 3,
          book: "2 Nefi",
          chapter: 5,
          narrator: "Patrizia Conforte",
          narratorImageName: "PatriziaConforte",
          chapterImageName: "2Nephi5",
          audioFileName: "2Nefi5",
          isActiveBookmark: false,
          src: "assets/media/2Nefi5.mp3",
        },
        {
          uuid: 33,
          bookID: 3,
          book: "2 Nefi",
          chapter: 6,
          narrator: "Vittoria Todisco",
          narratorImageName: "VittoriaTodisco",
          chapterImageName: "2Nephi6",
          audioFileName: "2Nefi6",
          isActiveBookmark: false,
          src: "assets/media/2Nefi6.mp3",
        },
        {
          uuid: 34,
          bookID: 3,
          book: "2 Nefi",
          chapter: 7,
          narrator: "Dario De Angelis",
          narratorImageName: "DarioDeAngelis",
          chapterImageName: "2Nephi7",
          audioFileName: "2Nefi7",
          isActiveBookmark: false,
          src: "assets/media/2Nefi7.mp3",
        },
        {
          uuid: 35,
          bookID: 3,
          book: "2 Nefi",
          chapter: 8,
          narrator: "Rinaldo Paoletti",
          narratorImageName: "RinaldoPaoletti",
          chapterImageName: "2Nephi8",
          audioFileName: "2Nefi8",
          isActiveBookmark: false,
          src: "assets/media/2Nefi8.mp3",
        },
        {
          uuid: 36,
          bookID: 3,
          book: "2 Nefi",
          chapter: 9,
          narrator: "Sara Purpari",
          narratorImageName: "SaraPurpari",
          chapterImageName: "2Nephi9",
          audioFileName: "2Nefi9",
          isActiveBookmark: false,
          src: "assets/media/2Nefi9.mp3",
        },
        {
          uuid: 37,
          bookID: 3,
          book: "2 Nefi",
          chapter: 10,
          narrator: "Maurizio Conforte",
          narratorImageName: "MaurizioConforte",
          chapterImageName: "2Nephi10",
          audioFileName: "2Nefi10",
          isActiveBookmark: false,
          src: "assets/media/2Nefi10.mp3",
        },
        {
          uuid: 38,
          bookID: 3,
          book: "2 Nefi",
          chapter: 11,
          narrator: "Stefania Tonon",
          narratorImageName: "StefaniaTonon",
          chapterImageName: "BOMpic",
          audioFileName: "2Nefi11",
          isActiveBookmark: false,
          src: "assets/media/2Nefi11.mp3",
        },
        {
          uuid: 39,
          bookID: 3,
          book: "2 Nefi",
          chapter: 12,
          narrator: "Santo Rosato",
          narratorImageName: "SantoRosato",
          chapterImageName: "BOMpic",
          audioFileName: "2Nefi12",
          isActiveBookmark: false,
          src: "assets/media/2Nefi12.mp3",
        },
        {
          uuid: 40,
          bookID: 3,
          book: "2 Nefi",
          chapter: 13,
          narrator: "Rita Pollina",
          narratorImageName: "RitaPollina",
          chapterImageName: "BOMpic",
          audioFileName: "2Nefi13",
          isActiveBookmark: false,
          src: "assets/media/2Nefi13.mp3",
        },
        {
          uuid: 41,
          bookID: 3,
          book: "2 Nefi",
          chapter: 14,
          narrator: "Nicolò Rodio",
          narratorImageName: "NicoloRodio",
          chapterImageName: "BOMpic",
          audioFileName: "2Nefi14",
          isActiveBookmark: false,
          src: "assets/media/2Nefi14.mp3",
        },
        {
          uuid: 42,
          bookID: 3,
          book: "2 Nefi",
          chapter: 15,
          narrator: "Eleonora Caravella",
          narratorImageName: "EleonoraCaravella",
          chapterImageName: "BOMpic",
          audioFileName: "2Nefi15",
          isActiveBookmark: false,
          src: "assets/media/2Nefi15.mp3",
        },
        {
          uuid: 43,
          bookID: 3,
          book: "2 Nefi",
          chapter: 16,
          narrator: "Nico Calabrese",
          narratorImageName: "NicoCalabrese",
          chapterImageName: "BOMpic",
          audioFileName: "2Nefi16",
          isActiveBookmark: false,
          src: "assets/media/2Nefi16.mp3",
        },
        {
          uuid: 44,
          bookID: 3,
          book: "2 Nefi",
          chapter: 17,
          narrator: "Davide Dicarolo",
          narratorImageName: "DavideDicarolo",
          chapterImageName: "BOMpic",
          audioFileName: "2Nefi17",
          isActiveBookmark: false,
          src: "assets/media/2Nefi17.mp3",
        },
        {
          uuid: 45,
          bookID: 3,
          book: "2 Nefi",
          chapter: 18,
          narrator: "Giulia Redaelli",
          narratorImageName: "GiuliaRedaelli",
          chapterImageName: "BOMpic",
          audioFileName: "2Nefi18",
          isActiveBookmark: false,
          src: "assets/media/2Nefi18.mp3",
        },
        {
          uuid: 46,
          bookID: 3,
          book: "2 Nefi",
          chapter: 19,
          narrator: "Carmelo Persico",
          narratorImageName: "CarmeloPersico",
          chapterImageName: "BOMpic",
          audioFileName: "2Nefi19",
          isActiveBookmark: false,
          src: "assets/media/2Nefi19.mp3",
        },
        {
          uuid: 47,
          bookID: 3,
          book: "2 Nefi",
          chapter: 20,
          narrator: "Gaia Pappalardo",
          narratorImageName: "GaiaPappalardo",
          chapterImageName: "BOMpic",
          audioFileName: "2Nefi20",
          isActiveBookmark: false,
          src: "assets/media/2Nefi20.mp3",
        },
        {
          uuid: 48,
          bookID: 3,
          book: "2 Nefi",
          chapter: 21,
          narrator: "Alessandro Cusumano",
          narratorImageName: "AlessandroCusumano",
          chapterImageName: "BOMpic",
          audioFileName: "2Nefi21",
          isActiveBookmark: false,
          src: "assets/media/2Nefi21.mp3",
        },
        {
          uuid: 49,
          bookID: 3,
          book: "2 Nefi",
          chapter: 22,
          narrator: "Andrea Cusumano",
          narratorImageName: "AndreaCusumano",
          chapterImageName: "BOMpic",
          audioFileName: "2Nefi22",
          isActiveBookmark: false,
          src: "assets/media/2Nefi22.mp3",
        },
        {
          uuid: 50,
          bookID: 3,
          book: "2 Nefi",
          chapter: 23,
          narrator: "Florinda Ferreri",
          narratorImageName: "FlorindaFerreri",
          chapterImageName: "BOMpic",
          audioFileName: "2Nefi23",
          isActiveBookmark: false,
          src: "assets/media/2Nefi23.mp3",
        },
        {
          uuid: 51,
          bookID: 3,
          book: "2 Nefi",
          chapter: 24,
          narrator: "Francesco Mannino",
          narratorImageName: "FrancescoMannino",
          chapterImageName: "BOMpic",
          audioFileName: "2Nefi24",
          isActiveBookmark: false,
          src: "assets/media/2Nefi24.mp3",
        },
        {
          uuid: 52,
          bookID: 3,
          book: "2 Nefi",
          chapter: 25,
          narrator: "Letizia Furia",
          narratorImageName: "LetiziaFuria",
          chapterImageName: "BOMpic",
          audioFileName: "2Nefi25",
          isActiveBookmark: false,
          src: "assets/media/2Nefi25.mp3",
        },
        {
          uuid: 53,
          bookID: 3,
          book: "2 Nefi",
          chapter: 26,
          narrator: "Noemi Tonon",
          narratorImageName: "NoemiTonon",
          chapterImageName: "BOMpic",
          audioFileName: "2Nefi26",
          isActiveBookmark: false,
          src: "assets/media/2Nefi26.mp3",
        },
        {
          uuid: 54,
          bookID: 3,
          book: "2 Nefi",
          chapter: 27,
          narrator: "Emanuel Tribaudino",
          narratorImageName: "EmanuelTribaudino",
          chapterImageName: "BOMpic",
          audioFileName: "2Nefi27",
          isActiveBookmark: false,
          src: "assets/media/2Nefi27.mp3",
        },
        {
          uuid: 55,
          bookID: 3,
          book: "2 Nefi",
          chapter: 28,
          narrator: "Davide Dicarolo",
          narratorImageName: "DavideDicarolo",
          chapterImageName: "BOMpic",
          audioFileName: "2Nefi28",
          isActiveBookmark: false,
          src: "assets/media/2Nefi28.mp3",
        },
        {
          uuid: 56,
          bookID: 3,
          book: "2 Nefi",
          chapter: 29,
          narrator: "Olimpia Diodato",
          narratorImageName: "OlimpiaDiodato",
          chapterImageName: "BOMpic",
          audioFileName: "2Nefi29",
          isActiveBookmark: false,
          src: "assets/media/2Nefi29.mp3",
        },
        {
          uuid: 57,
          bookID: 3,
          book: "2 Nefi",
          chapter: 30,
          narrator: "Giulia  Diodato",
          narratorImageName: "GiuliaDiodato",
          chapterImageName: "BOMpic",
          audioFileName: "2Nefi30",
          isActiveBookmark: false,
          src: "assets/media/2Nefi30.mp3",
        },
        {
          uuid: 58,
          bookID: 3,
          book: "2 Nefi",
          chapter: 31,
          narrator: "Thomas Tonon",
          narratorImageName: "ThomasTonon",
          chapterImageName: "2Nephi31",
          audioFileName: "2Nefi31",
          isActiveBookmark: false,
          src: "assets/media/2Nefi31.mp3",
        },
        {
          uuid: 59,
          bookID: 3,
          book: "2 Nefi",
          chapter: 32,
          narrator: "Morgan Tonon",
          narratorImageName: "MorganTonon",
          chapterImageName: "2Nephi32",
          audioFileName: "2Nefi32",
          isActiveBookmark: false,
          src: "assets/media/2Nefi32.mp3",
        },
        {
          uuid: 60,
          bookID: 3,
          book: "2 Nefi",
          chapter: 33,
          narrator: "Bruno Diodato",
          narratorImageName: "BrunoDiodato",
          chapterImageName: "BOMpic",
          audioFileName: "2Nefi33",
          isActiveBookmark: false,
          src: "assets/media/2Nefi33.mp3",
        },
        {
          uuid: 61,
          bookID: 4,
          book: "Giacobbe",
          chapter: 1,
          narrator: "Andrea Bertocchi",
          narratorImageName: "AndreaBertocchi",
          chapterImageName: "BOMpic",
          audioFileName: "Giacobbe1",
          isActiveBookmark: false,
          src: "assets/media/Giacobbe1.mp3",
        },
        {
          uuid: 62,
          bookID: 4,
          book: "Giacobbe",
          chapter: 2,
          narrator: "Giovanni Dal Pozzo",
          narratorImageName: "GiovanniDalPozzo",
          chapterImageName: "BOMpic",
          audioFileName: "Giacobbe2",
          isActiveBookmark: false,
          src: "assets/media/Giacobbe2.mp3",
        },
        {
          uuid: 63,
          bookID: 4,
          book: "Giacobbe",
          chapter: 3,
          narrator: "Francesco Rodio",
          narratorImageName: "FrancescoRodio",
          chapterImageName: "BOMpic",
          audioFileName: "Giacobbe3",
          isActiveBookmark: false,
          src: "assets/media/Giacobbe3.mp3",
        },
        {
          uuid: 64,
          bookID: 4,
          book: "Giacobbe",
          chapter: 4,
          narrator: "Silvia Rodio",
          narratorImageName: "SilviaRodio",
          chapterImageName: "BOMpic",
          audioFileName: "Giacobbe4",
          isActiveBookmark: false,
          src: "assets/media/Giacobbe4.mp3",
        },
        {
          uuid: 65,
          bookID: 4,
          book: "Giacobbe",
          chapter: 5,
          narrator: "Elisa Carrus Giolitto",
          narratorImageName: "ElisaCarrusGiolitto",
          chapterImageName: "BOMpic",
          audioFileName: "Giacobbe5",
          isActiveBookmark: false,
          src: "assets/media/Giacobbe5.mp3",
        },
        {
          uuid: 66,
          bookID: 4,
          book: "Giacobbe",
          chapter: 6,
          narrator: "Sara Sisto",
          narratorImageName: "SaraSisto",
          chapterImageName: "BOMpic",
          audioFileName: "Giacobbe6",
          isActiveBookmark: false,
          src: "assets/media/Giacobbe6.mp3",
        },
        {
          uuid: 67,
          bookID: 4,
          book: "Giacobbe",
          chapter: 7,
          narrator: "Anna Maria Zilli",
          narratorImageName: "AnnaMariaZilli",
          chapterImageName: "BOMpic",
          audioFileName: "Giacobbe7",
          isActiveBookmark: false,
          src: "assets/media/Giacobbe7.mp3",
        },
        {
          uuid: 68,
          bookID: 5,
          book: "Enos",
          chapter: 1,
          narrator: "Grazia Conforte",
          narratorImageName: "GraziaConforte",
          chapterImageName: "BOMpic",
          audioFileName: "Enos1",
          isActiveBookmark: false,
          src: "assets/media/Enos1.mp3",
        },
        {
          uuid: 69,
          bookID: 6,
          book: "Giarom",
          chapter: 1,
          narrator: "Cristina Perricone",
          narratorImageName: "CristinaPerricone",
          chapterImageName: "BOMpic",
          audioFileName: "Giarom1",
          isActiveBookmark: false,
          src: "assets/media/Giarom1.mp3",
        },
        {
          uuid: 70,
          bookID: 7,
          book: "Omni",
          chapter: 1,
          narrator: "Noemi Tribaudino",
          narratorImageName: "NoemiTribaudino",
          chapterImageName: "Omni1",
          audioFileName: "Omni1",
          isActiveBookmark: false,
          src: "assets/media/Omni1.mp3",
        },
        {
          uuid: 71,
          bookID: 8,
          book: "Parole di Mormon",
          chapter: 1,
          narrator: "Katia Carrara",
          narratorImageName: "KatiaCarrara",
          chapterImageName: "WordsOfMormon1",
          audioFileName: "ParolediMormon1",
          isActiveBookmark: false,
          src: "assets/media/ParolediMormon1.mp3",
        },
        {
          uuid: 72,
          bookID: 9,
          book: "Mosia",
          chapter: 1,
          narrator: "Stefania Tonon",
          narratorImageName: "StefaniaTonon",
          chapterImageName: "Mosiah1",
          audioFileName: "Mosia1",
          isActiveBookmark: false,
          src: "assets/media/Mosia1.mp3",
        },
        {
          uuid: 73,
          bookID: 9,
          book: "Mosia",
          chapter: 2,
          narrator: "Francesca Di Ruscio",
          narratorImageName: "FrancescaDiRuscio",
          chapterImageName: "Mosiah2",
          audioFileName: "Mosia2",
          isActiveBookmark: false,
          src: "assets/media/Mosia2.mp3",
        },
        {
          uuid: 74,
          bookID: 9,
          book: "Mosia",
          chapter: 3,
          narrator: "Daniele Dicarolo",
          narratorImageName: "DanieleDicarolo",
          chapterImageName: "BOMpic",
          audioFileName: "Mosia3",
          isActiveBookmark: false,
          src: "assets/media/Mosia3.mp3",
        },
        {
          uuid: 75,
          bookID: 9,
          book: "Mosia",
          chapter: 4,
          narrator: "Francesca Lui",
          narratorImageName: "FrancescaLui",
          chapterImageName: "BOMpic",
          audioFileName: "Mosia4",
          isActiveBookmark: false,
          src: "assets/media/Mosia4.mp3",
        },
        {
          uuid: 76,
          bookID: 9,
          book: "Mosia",
          chapter: 5,
          narrator: "Franco Mangifesta",
          narratorImageName: "FrancoMangifesta",
          chapterImageName: "BOMpic",
          audioFileName: "Mosia5",
          isActiveBookmark: false,
          src: "assets/media/Mosia5.mp3",
        },
        {
          uuid: 77,
          bookID: 9,
          book: "Mosia",
          chapter: 6,
          narrator: "Nicolò Rodio",
          narratorImageName: "NicoloRodio",
          chapterImageName: "BOMpic",
          audioFileName: "Mosia6",
          isActiveBookmark: false,
          src: "assets/media/Mosia6.mp3",
        },
        {
          uuid: 78,
          bookID: 9,
          book: "Mosia",
          chapter: 7,
          narrator: "Alexandra Pavesi",
          narratorImageName: "AlexandraPavesi",
          chapterImageName: "BOMpic",
          audioFileName: "Mosia7",
          isActiveBookmark: false,
          src: "assets/media/Mosia7.mp3",
        },
        {
          uuid: 79,
          bookID: 9,
          book: "Mosia",
          chapter: 8,
          narrator: "Silvio Pirondini",
          narratorImageName: "SilvioPirondini",
          chapterImageName: "BOMpic",
          audioFileName: "Mosia8",
          isActiveBookmark: false,
          src: "assets/media/Mosia8.mp3",
        },
        {
          uuid: 80,
          bookID: 9,
          book: "Mosia",
          chapter: 9,
          narrator: "Vittorio Salemi",
          narratorImageName: "VittorioSalemi",
          chapterImageName: "BOMpic",
          audioFileName: "Mosia9",
          isActiveBookmark: false,
          src: "assets/media/Mosia9.mp3",
        },
        {
          uuid: 81,
          bookID: 9,
          book: "Mosia",
          chapter: 10,
          narrator: "Donata Pirondini",
          narratorImageName: "DonataPirondini",
          chapterImageName: "BOMpic",
          audioFileName: "Mosia10",
          isActiveBookmark: false,
          src: "assets/media/Mosia10.mp3",
        },
        {
          uuid: 82,
          bookID: 9,
          book: "Mosia",
          chapter: 11,
          narrator: "Michele Argenti",
          narratorImageName: "MicheleArgenti",
          chapterImageName: "Mosiah11",
          audioFileName: "Mosia11",
          isActiveBookmark: false,
          src: "assets/media/Mosia11.mp3",
        },
        {
          uuid: 83,
          bookID: 9,
          book: "Mosia",
          chapter: 12,
          narrator: "Daniele Lui",
          narratorImageName: "DanieleLui",
          chapterImageName: "BOMpic",
          audioFileName: "Mosia12",
          isActiveBookmark: false,
          src: "assets/media/Mosia12.mp3",
        },
        {
          uuid: 84,
          bookID: 9,
          book: "Mosia",
          chapter: 13,
          narrator: "Anna Maria Zilli",
          narratorImageName: "AnnaMariaZilli",
          chapterImageName: "Mosiah13",
          audioFileName: "Mosia13",
          isActiveBookmark: false,
          src: "assets/media/Mosia13.mp3",
        },
        {
          uuid: 85,
          bookID: 9,
          book: "Mosia",
          chapter: 14,
          narrator: "Gabriele Teodosi",
          narratorImageName: "GabrieleTeodosi",
          chapterImageName: "BOMpic",
          audioFileName: "Mosia14",
          isActiveBookmark: false,
          src: "assets/media/Mosia14.mp3",
        },
        {
          uuid: 86,
          bookID: 9,
          book: "Mosia",
          chapter: 15,
          narrator: "Buonfiglio Petroni",
          narratorImageName: "BuonfiglioPetroni",
          chapterImageName: "BOMpic",
          audioFileName: "Mosia15",
          isActiveBookmark: false,
          src: "assets/media/Mosia15.mp3",
        },
        {
          uuid: 87,
          bookID: 9,
          book: "Mosia",
          chapter: 16,
          narrator: "Cristiana Baldassi",
          narratorImageName: "CristianaBaldassi",
          chapterImageName: "BOMpic",
          audioFileName: "Mosia16",
          isActiveBookmark: false,
          src: "assets/media/Mosia16.mp3",
        },
        {
          uuid: 88,
          bookID: 9,
          book: "Mosia",
          chapter: 17,
          narrator: "Nicoletta Pagnani",
          narratorImageName: "NicolettaPagnani",
          chapterImageName: "BOMpic",
          audioFileName: "Mosia17",
          isActiveBookmark: false,
          src: "assets/media/Mosia17.mp3",
        },
        {
          uuid: 89,
          bookID: 9,
          book: "Mosia",
          chapter: 18,
          narrator: "Daniele Casella",
          narratorImageName: "DanieleCasella",
          chapterImageName: "Mosiah18",
          audioFileName: "Mosia18",
          isActiveBookmark: false,
          src: "assets/media/Mosia18.mp3",
        },
        {
          uuid: 90,
          bookID: 9,
          book: "Mosia",
          chapter: 19,
          narrator: "Roberta Marinello",
          narratorImageName: "RobertaMarinello",
          chapterImageName: "Mosiah19",
          audioFileName: "Mosia19",
          isActiveBookmark: false,
          src: "assets/media/Mosia19.mp3",
        },
        {
          uuid: 91,
          bookID: 9,
          book: "Mosia",
          chapter: 20,
          narrator: "Marianna Pastano",
          narratorImageName: "MariannaPastano",
          chapterImageName: "BOMpic",
          audioFileName: "Mosia20",
          isActiveBookmark: false,
          src: "assets/media/Mosia20.mp3",
        },
        {
          uuid: 92,
          bookID: 9,
          book: "Mosia",
          chapter: 21,
          narrator: "Ugo Perego",
          narratorImageName: "UgoPerego",
          chapterImageName: "BOMpic",
          audioFileName: "Mosia21",
          isActiveBookmark: false,
          src: "assets/media/Mosia21.mp3",
        },
        {
          uuid: 93,
          bookID: 9,
          book: "Mosia",
          chapter: 22,
          narrator: "Giuliana Dal Zotto",
          narratorImageName: "GiulianaDalZotto",
          chapterImageName: "Mosiah22",
          audioFileName: "Mosia22",
          isActiveBookmark: false,
          src: "assets/media/Mosia22.mp3",
        },
        {
          uuid: 94,
          bookID: 9,
          book: "Mosia",
          chapter: 23,
          narrator: "Valter Buono",
          narratorImageName: "ValterBuono",
          chapterImageName: "BOMpic",
          audioFileName: "Mosia23",
          isActiveBookmark: false,
          src: "assets/media/Mosia23.mp3",
        },
        {
          uuid: 95,
          bookID: 9,
          book: "Mosia",
          chapter: 24,
          narrator: "Fernando Curci",
          narratorImageName: "FernandoCurci",
          chapterImageName: "BOMpic",
          audioFileName: "Mosia24",
          isActiveBookmark: false,
          src: "assets/media/Mosia24.mp3",
        },
        {
          uuid: 96,
          bookID: 9,
          book: "Mosia",
          chapter: 25,
          narrator: "Tranquillo Dal Zotto",
          narratorImageName: "TranquilloDalZotto",
          chapterImageName: "BOMpic",
          audioFileName: "Mosia25",
          isActiveBookmark: false,
          src: "assets/media/Mosia25.mp3",
        },
        {
          uuid: 97,
          bookID: 9,
          book: "Mosia",
          chapter: 26,
          narrator: "Elisabetta Calabrese",
          narratorImageName: "ElisabettaCalabrese",
          chapterImageName: "BOMpic",
          audioFileName: "Mosia26",
          isActiveBookmark: false,
          src: "assets/media/Mosia26.mp3",
        },
        {
          uuid: 98,
          bookID: 9,
          book: "Mosia",
          chapter: 27,
          narrator: "Giorgia Castorina",
          narratorImageName: "GiorgiaCastorina",
          chapterImageName: "Mosiah27",
          audioFileName: "Mosia27",
          isActiveBookmark: false,
          src: "assets/media/Mosia27.mp3",
        },
        {
          uuid: 99,
          bookID: 9,
          book: "Mosia",
          chapter: 28,
          narrator: "Umberto Pagnani",
          narratorImageName: "UmbertoPagnani",
          chapterImageName: "BOMpic",
          audioFileName: "Mosia28",
          isActiveBookmark: false,
          src: "assets/media/Mosia28.mp3",
        },
        {
          uuid: 100,
          bookID: 9,
          book: "Mosia",
          chapter: 29,
          narrator: "Silvia Guidara",
          narratorImageName: "SilviaGuidara",
          chapterImageName: "BOMpic",
          audioFileName: "Mosia29",
          isActiveBookmark: false,
          src: "assets/media/Mosia29.mp3",
        },
        {
          uuid: 101,
          bookID: 10,
          book: "Alma",
          chapter: 1,
          narrator: "Settimia Lui",
          narratorImageName: "SettimiaLui",
          chapterImageName: "BOMpic",
          audioFileName: "Alma1",
          isActiveBookmark: false,
          src: "assets/media/Alma1.mp3",
        },
        {
          uuid: 102,
          bookID: 10,
          book: "Alma",
          chapter: 2,
          narrator: "Gabriele Di Liberto",
          narratorImageName: "GabrieleDiLiberto",
          chapterImageName: "BOMpic",
          audioFileName: "Alma2",
          isActiveBookmark: false,
          src: "assets/media/Alma2.mp3",
        },
        {
          uuid: 103,
          bookID: 10,
          book: "Alma",
          chapter: 3,
          narrator: "Federica Netto",
          narratorImageName: "FedericaNetto",
          chapterImageName: "BOMpic",
          audioFileName: "Alma3",
          isActiveBookmark: false,
          src: "assets/media/Alma3.mp3",
        },
        {
          uuid: 104,
          bookID: 10,
          book: "Alma",
          chapter: 4,
          narrator: "Alexandra Pavesi",
          narratorImageName: "AlexandraPavesi",
          chapterImageName: "BOMpic",
          audioFileName: "Alma4",
          isActiveBookmark: false,
          src: "assets/media/Alma4.mp3",
        },
        {
          uuid: 105,
          bookID: 10,
          book: "Alma",
          chapter: 5,
          narrator: "Miriam Bressan",
          narratorImageName: "MiriamBressan",
          chapterImageName: "BOMpic",
          audioFileName: "Alma5",
          isActiveBookmark: false,
          src: "assets/media/Alma5.mp3",
        },
        {
          uuid: 106,
          bookID: 10,
          book: "Alma",
          chapter: 6,
          narrator: "Giovanni Pulvirenti",
          narratorImageName: "GiovanniPulvirenti",
          chapterImageName: "BOMpic",
          audioFileName: "Alma6",
          isActiveBookmark: false,
          src: "assets/media/Alma6.mp3",
        },
        {
          uuid: 107,
          bookID: 10,
          book: "Alma",
          chapter: 7,
          narrator: "Elvisa De Santis",
          narratorImageName: "ElvisaDeSantis",
          chapterImageName: "BOMpic",
          audioFileName: "Alma7",
          isActiveBookmark: false,
          src: "assets/media/Alma7.mp3",
        },
        {
          uuid: 108,
          bookID: 10,
          book: "Alma",
          chapter: 8,
          narrator: "Melissa Reyes",
          narratorImageName: "MelissaReyes",
          chapterImageName: "BOMpic",
          audioFileName: "Alma8",
          isActiveBookmark: false,
          src: "assets/media/Alma8.mp3",
        },
        {
          uuid: 109,
          bookID: 10,
          book: "Alma",
          chapter: 9,
          narrator: "Antonio Murgia",
          narratorImageName: "AntonioMurgia",
          chapterImageName: "BOMpic",
          audioFileName: "Alma9",
          isActiveBookmark: false,
          src: "assets/media/Alma9.mp3",
        },
        {
          uuid: 110,
          bookID: 10,
          book: "Alma",
          chapter: 10,
          narrator: "Maria Chiara Murgia",
          narratorImageName: "MariaMurgia",
          chapterImageName: "BOMpic",
          audioFileName: "Alma10",
          isActiveBookmark: false,
          src: "assets/media/Alma10.mp3",
        },
        {
          uuid: 111,
          bookID: 10,
          book: "Alma",
          chapter: 11,
          narrator: "Edoardo Iob",
          narratorImageName: "EdoardoIob",
          chapterImageName: "BOMpic",
          audioFileName: "Alma11",
          isActiveBookmark: false,
          src: "assets/media/Alma11.mp3",
        },
        {
          uuid: 112,
          bookID: 10,
          book: "Alma",
          chapter: 12,
          narrator: "Edoardo Iob",
          narratorImageName: "EdoardoIob",
          chapterImageName: "BOMpic",
          audioFileName: "Alma12",
          isActiveBookmark: false,
          src: "assets/media/Alma12.mp3",
        },
        {
          uuid: 113,
          bookID: 10,
          book: "Alma",
          chapter: 13,
          narrator: "Matteo Lusso",
          narratorImageName: "MatteoLusso",
          chapterImageName: "BOMpic",
          audioFileName: "Alma13",
          isActiveBookmark: false,
          src: "assets/media/Alma13.mp3",
        },
        {
          uuid: 114,
          bookID: 10,
          book: "Alma",
          chapter: 14,
          narrator: "Vincenzo Saeli",
          narratorImageName: "VincenzoSaeli",
          chapterImageName: "Alma14",
          audioFileName: "Alma14",
          isActiveBookmark: false,
          src: "assets/media/Alma14.mp3",
        },
        {
          uuid: 115,
          bookID: 10,
          book: "Alma",
          chapter: 15,
          narrator: "Gaspar Lazarte",
          narratorImageName: "GasparLazarte",
          chapterImageName: "BOMpic",
          audioFileName: "Alma15",
          isActiveBookmark: false,
          src: "assets/media/Alma15.mp3",
        },
        {
          uuid: 116,
          bookID: 10,
          book: "Alma",
          chapter: 16,
          narrator: "Volodymyr Prystupa",
          narratorImageName: "VolodymyrPrystupa",
          chapterImageName: "BOMpic",
          audioFileName: "Alma16",
          isActiveBookmark: false,
          src: "assets/media/Alma16.mp3",
        },
        {
          uuid: 117,
          bookID: 10,
          book: "Alma",
          chapter: 17,
          narrator: "Francesco Locorotondo",
          narratorImageName: "FrancescoLocorotondo",
          chapterImageName: "Alma17",
          audioFileName: "Alma17",
          isActiveBookmark: false,
          src: "assets/media/Alma17.mp3",
        },
        {
          uuid: 118,
          bookID: 10,
          book: "Alma",
          chapter: 18,
          narrator: "Francesco Fasano",
          narratorImageName: "FrancescoFasano",
          chapterImageName: "Alma18",
          audioFileName: "Alma18",
          isActiveBookmark: false,
          src: "assets/media/Alma18.mp3",
        },
        {
          uuid: 119,
          bookID: 10,
          book: "Alma",
          chapter: 19,
          narrator: "Naomi Armenise",
          narratorImageName: "NaomiArmenise",
          chapterImageName: "BOMpic",
          audioFileName: "Alma19",
          isActiveBookmark: false,
          src: "assets/media/Alma19.mp3",
        },
        {
          uuid: 120,
          bookID: 10,
          book: "Alma",
          chapter: 20,
          narrator: "Patrizia Conforte",
          narratorImageName: "PatriziaConforte",
          chapterImageName: "Alma20",
          audioFileName: "Alma20",
          isActiveBookmark: false,
          src: "assets/media/Alma20.mp3",
        },
        {
          uuid: 121,
          bookID: 10,
          book: "Alma",
          chapter: 21,
          narrator: "Maria Arcidiacano",
          narratorImageName: "MariaArcidiacano",
          chapterImageName: "BOMpic",
          audioFileName: "Alma21",
          isActiveBookmark: false,
          src: "assets/media/Alma21.mp3",
        },
        {
          uuid: 122,
          bookID: 10,
          book: "Alma",
          chapter: 22,
          narrator: "Francesco Fasano",
          narratorImageName: "FrancescoFasano",
          chapterImageName: "BOMpic",
          audioFileName: "Alma22",
          isActiveBookmark: false,
          src: "assets/media/Alma22.mp3",
        },
        {
          uuid: 123,
          bookID: 10,
          book: "Alma",
          chapter: 23,
          narrator: "Venerina Malara",
          narratorImageName: "VenerinaMalara",
          chapterImageName: "BOMpic",
          audioFileName: "Alma23",
          isActiveBookmark: false,
          src: "assets/media/Alma23.mp3",
        },
        {
          uuid: 124,
          bookID: 10,
          book: "Alma",
          chapter: 24,
          narrator: "Emily Cascone",
          narratorImageName: "EmilyCascone",
          chapterImageName: "Alma24",
          audioFileName: "Alma24",
          isActiveBookmark: false,
          src: "assets/media/Alma24.mp3",
        },
        {
          uuid: 125,
          bookID: 10,
          book: "Alma",
          chapter: 25,
          narrator: "Rosa Calabrese",
          narratorImageName: "RosaCalabrese",
          chapterImageName: "BOMpic",
          audioFileName: "Alma25",
          isActiveBookmark: false,
          src: "assets/media/Alma25.mp3",
        },
        {
          uuid: 126,
          bookID: 10,
          book: "Alma",
          chapter: 26,
          narrator: "Rebecca Bertone",
          narratorImageName: "RebeccaBertone",
          chapterImageName: "Alma26",
          audioFileName: "Alma26",
          isActiveBookmark: false,
          src: "assets/media/Alma26.mp3",
        },
        {
          uuid: 127,
          bookID: 10,
          book: "Alma",
          chapter: 27,
          narrator: "Debora Siniscalchi",
          narratorImageName: "DeboraSiniscalchi",
          chapterImageName: "BOMpic",
          audioFileName: "Alma27",
          isActiveBookmark: false,
          src: "assets/media/Alma27.mp3",
        },
        {
          uuid: 128,
          bookID: 10,
          book: "Alma",
          chapter: 28,
          narrator: "Settimia Lui",
          narratorImageName: "SettimiaLui",
          chapterImageName: "BOMpic",
          audioFileName: "Alma28",
          isActiveBookmark: false,
          src: "assets/media/Alma28.mp3",
        },
        {
          uuid: 129,
          bookID: 10,
          book: "Alma",
          chapter: 29,
          narrator: "Miriam Bressan",
          narratorImageName: "MiriamBressan",
          chapterImageName: "BOMpic",
          audioFileName: "Alma29",
          isActiveBookmark: false,
          src: "assets/media/Alma29.mp3",
        },
        {
          uuid: 130,
          bookID: 10,
          book: "Alma",
          chapter: 30,
          narrator: "Elisa Carrus Giolitto",
          narratorImageName: "ElisaCarrusGiolitto",
          chapterImageName: "Alma30",
          audioFileName: "Alma30",
          isActiveBookmark: false,
          src: "assets/media/Alma30.mp3",
        },
        {
          uuid: 131,
          bookID: 10,
          book: "Alma",
          chapter: 31,
          narrator: "Morgan Tonon",
          narratorImageName: "MorganTonon",
          chapterImageName: "Alma31",
          audioFileName: "Alma31",
          isActiveBookmark: false,
          src: "assets/media/Alma31.mp3",
        },
        {
          uuid: 132,
          bookID: 10,
          book: "Alma",
          chapter: 32,
          narrator: "Cristina Perricone",
          narratorImageName: "CristinaPerricone",
          chapterImageName: "Alma32",
          audioFileName: "Alma32",
          isActiveBookmark: false,
          src: "assets/media/Alma32.mp3",
        },
        {
          uuid: 133,
          bookID: 10,
          book: "Alma",
          chapter: 33,
          narrator: "Stefano Pace",
          narratorImageName: "StefanoPace",
          chapterImageName: "BOMpic",
          audioFileName: "Alma33",
          isActiveBookmark: false,
          src: "assets/media/Alma33.mp3",
        },
        {
          uuid: 134,
          bookID: 10,
          book: "Alma",
          chapter: 34,
          narrator: "Emanuele Cascone",
          narratorImageName: "EmanueleCascone",
          chapterImageName: "BOMpic",
          audioFileName: "Alma34",
          isActiveBookmark: false,
          src: "assets/media/Alma34.mp3",
        },
        {
          uuid: 135,
          bookID: 10,
          book: "Alma",
          chapter: 35,
          narrator: "Jeimy Sisto",
          narratorImageName: "JeimySisto",
          chapterImageName: "BOMpic",
          audioFileName: "Alma35",
          isActiveBookmark: false,
          src: "assets/media/Alma35.mp3",
        },
        {
          uuid: 136,
          bookID: 10,
          book: "Alma",
          chapter: 36,
          narrator: "Marialuisa Di Liberto",
          narratorImageName: "MarialuisaDiLiberto",
          chapterImageName: "Alma36",
          audioFileName: "Alma36",
          isActiveBookmark: false,
          src: "assets/media/Alma36.mp3",
        },
        {
          uuid: 137,
          bookID: 10,
          book: "Alma",
          chapter: 37,
          narrator: "Jessica Caramia",
          narratorImageName: "JessicaCaramia",
          chapterImageName: "Alma37",
          audioFileName: "Alma37",
          isActiveBookmark: false,
          src: "assets/media/Alma37.mp3",
        },
        {
          uuid: 138,
          bookID: 10,
          book: "Alma",
          chapter: 38,
          narrator: "Marilene Rossetti",
          narratorImageName: "MarileneRossetti",
          chapterImageName: "BOMpic",
          audioFileName: "Alma38",
          isActiveBookmark: false,
          src: "assets/media/Alma38.mp3",
        },
        {
          uuid: 139,
          bookID: 10,
          book: "Alma",
          chapter: 39,
          narrator: "Domenico Corvasce",
          narratorImageName: "DomenicoCorvasce",
          chapterImageName: "BOMpic",
          audioFileName: "Alma39",
          isActiveBookmark: false,
          src: "assets/media/Alma39.mp3",
        },
        {
          uuid: 140,
          bookID: 10,
          book: "Alma",
          chapter: 40,
          narrator: "Davide Dicarolo",
          narratorImageName: "DavideDicarolo",
          chapterImageName: "BOMpic",
          audioFileName: "Alma40",
          isActiveBookmark: false,
          src: "assets/media/Alma40.mp3",
        },
        {
          uuid: 141,
          bookID: 10,
          book: "Alma",
          chapter: 41,
          narrator: "Igea Locorotondo",
          narratorImageName: "IgeaLocorotondo",
          chapterImageName: "BOMpic",
          audioFileName: "Alma41",
          isActiveBookmark: false,
          src: "assets/media/Alma41.mp3",
        },
        {
          uuid: 142,
          bookID: 10,
          book: "Alma",
          chapter: 42,
          narrator: "Joshua Corvasce",
          narratorImageName: "JoshuaCorvasce",
          chapterImageName: "BOMpic",
          audioFileName: "Alma42",
          isActiveBookmark: false,
          src: "assets/media/Alma42.mp3",
        },
        {
          uuid: 143,
          bookID: 10,
          book: "Alma",
          chapter: 43,
          narrator: "Carla Bertone",
          narratorImageName: "CarlaBertone",
          chapterImageName: "Alma43",
          audioFileName: "Alma43",
          isActiveBookmark: false,
          src: "assets/media/Alma43.mp3",
        },
        {
          uuid: 144,
          bookID: 10,
          book: "Alma",
          chapter: 44,
          narrator: "Pino Valle",
          narratorImageName: "PinoValle",
          chapterImageName: "Alma44",
          audioFileName: "Alma44",
          isActiveBookmark: false,
          src: "assets/media/Alma44.mp3",
        },
        {
          uuid: 145,
          bookID: 10,
          book: "Alma",
          chapter: 45,
          narrator: "Grazia Battezzato",
          narratorImageName: "GraziaBattezzato",
          chapterImageName: "BOMpic",
          audioFileName: "Alma45",
          isActiveBookmark: false,
          src: "assets/media/Alma45.mp3",
        },
        {
          uuid: 146,
          bookID: 10,
          book: "Alma",
          chapter: 46,
          narrator: "Micol Bressan",
          narratorImageName: "MicolBressan",
          chapterImageName: "Alma46",
          audioFileName: "Alma46",
          isActiveBookmark: false,
          src: "assets/media/Alma46.mp3",
        },
        {
          uuid: 147,
          bookID: 10,
          book: "Alma",
          chapter: 47,
          narrator: "Giacomo Bressan",
          narratorImageName: "GiacomoBressan",
          chapterImageName: "BOMpic",
          audioFileName: "Alma47",
          isActiveBookmark: false,
          src: "assets/media/Alma47.mp3",
        },
        {
          uuid: 148,
          bookID: 10,
          book: "Alma",
          chapter: 48,
          narrator: "Perla Pulvirenti",
          narratorImageName: "PerlaPulvirenti",
          chapterImageName: "BOMpic",
          audioFileName: "Alma48",
          isActiveBookmark: false,
          src: "assets/media/Alma48.mp3",
        },
        {
          uuid: 149,
          bookID: 10,
          book: "Alma",
          chapter: 49,
          narrator: "Joy Pulvirenti",
          narratorImageName: "JoyPulvirenti",
          chapterImageName: "BOMpic",
          audioFileName: "Alma49",
          isActiveBookmark: false,
          src: "assets/media/Alma49.mp3",
        },
        {
          uuid: 150,
          bookID: 10,
          book: "Alma",
          chapter: 50,
          narrator: "Giuseppe Pulvirenti",
          narratorImageName: "GiuseppePulvirenti",
          chapterImageName: "BOMpic",
          audioFileName: "Alma50",
          isActiveBookmark: false,
          src: "assets/media/Alma50.mp3",
        },
        {
          uuid: 151,
          bookID: 10,
          book: "Alma",
          chapter: 51,
          narrator: "Giuseppe Pulvirenti",
          narratorImageName: "GiuseppePulvirenti",
          chapterImageName: "BOMpic",
          audioFileName: "Alma51",
          isActiveBookmark: false,
          src: "assets/media/Alma51.mp3",
        },
        {
          uuid: 152,
          bookID: 10,
          book: "Alma",
          chapter: 52,
          narrator: "Lorenzo Bertone",
          narratorImageName: "LorenzoBertone",
          chapterImageName: "BOMpic",
          audioFileName: "Alma52",
          isActiveBookmark: false,
          src: "assets/media/Alma52.mp3",
        },
        {
          uuid: 153,
          bookID: 10,
          book: "Alma",
          chapter: 53,
          narrator: "Angelika Iob",
          narratorImageName: "AngelikaIob",
          chapterImageName: "Alma53",
          audioFileName: "Alma53",
          isActiveBookmark: false,
          src: "assets/media/Alma53.mp3",
        },
        {
          uuid: 154,
          bookID: 10,
          book: "Alma",
          chapter: 54,
          narrator: "Daniela Caggese",
          narratorImageName: "DanielaCaggese",
          chapterImageName: "BOMpic",
          audioFileName: "Alma54",
          isActiveBookmark: false,
          src: "assets/media/Alma54.mp3",
        },
        {
          uuid: 155,
          bookID: 10,
          book: "Alma",
          chapter: 55,
          narrator: "Beatrice Dicarolo",
          narratorImageName: "BeatriceDicarolo",
          chapterImageName: "BOMpic",
          audioFileName: "Alma55",
          isActiveBookmark: false,
          src: "assets/media/Alma55.mp3",
        },
        {
          uuid: 156,
          bookID: 10,
          book: "Alma",
          chapter: 56,
          narrator: "Riccardo Vanoli",
          narratorImageName: "RiccardoVanoli",
          chapterImageName: "BOMpic",
          audioFileName: "Alma56",
          isActiveBookmark: false,
          src: "assets/media/Alma56.mp3",
        },
        {
          uuid: 157,
          bookID: 10,
          book: "Alma",
          chapter: 57,
          narrator: "Naomi Caramia",
          narratorImageName: "NaomiCaramia",
          chapterImageName: "BOMpic",
          audioFileName: "Alma57",
          isActiveBookmark: false,
          src: "assets/media/Alma57.mp3",
        },
        {
          uuid: 158,
          bookID: 10,
          book: "Alma",
          chapter: 58,
          narrator: "Naomi Caramia",
          narratorImageName: "NaomiCaramia",
          chapterImageName: "BOMpic",
          audioFileName: "Alma58",
          isActiveBookmark: false,
          src: "assets/media/Alma58.mp3",
        },
        {
          uuid: 159,
          bookID: 10,
          book: "Alma",
          chapter: 59,
          narrator: "Letizia Furia",
          narratorImageName: "LetiziaFuria",
          chapterImageName: "BOMpic",
          audioFileName: "Alma59",
          isActiveBookmark: false,
          src: "assets/media/Alma59.mp3",
        },
        {
          uuid: 160,
          bookID: 10,
          book: "Alma",
          chapter: 60,
          narrator: "Elisabetta Calabrese",
          narratorImageName: "ElisabettaCalabrese",
          chapterImageName: "BOMpic",
          audioFileName: "Alma60",
          isActiveBookmark: false,
          src: "assets/media/Alma60.mp3",
        },
        {
          uuid: 161,
          bookID: 10,
          book: "Alma",
          chapter: 61,
          narrator: "Chiara Cantoni",
          narratorImageName: "ChiaraCantoni",
          chapterImageName: "BOMpic",
          audioFileName: "Alma61",
          isActiveBookmark: false,
          src: "assets/media/Alma61.mp3",
        },
        {
          uuid: 162,
          bookID: 10,
          book: "Alma",
          chapter: 62,
          narrator: "Nancy Fiorillo",
          narratorImageName: "NancyFiorillo",
          chapterImageName: "BOMpic",
          audioFileName: "Alma62",
          isActiveBookmark: false,
          src: "assets/media/Alma62.mp3",
        },
        {
          uuid: 163,
          bookID: 10,
          book: "Alma",
          chapter: 63,
          narrator: "Francesca Di Ruscio",
          narratorImageName: "FrancescaDiRuscio",
          chapterImageName: "BOMpic",
          audioFileName: "Alma63",
          isActiveBookmark: false,
          src: "assets/media/Alma63.mp3",
        },
        {
          uuid: 164,
          bookID: 11,
          book: "Helaman",
          chapter: 1,
          narrator: "Giulia Redaelli",
          narratorImageName: "GiuliaRedaelli",
          chapterImageName: "BOMpic",
          audioFileName: "Helaman1",
          isActiveBookmark: false,
          src: "assets/media/Helaman1.mp3",
        },
        {
          uuid: 165,
          bookID: 11,
          book: "Helaman",
          chapter: 2,
          narrator: "Teresa Di Ruscio",
          narratorImageName: "TeresaDiRuscio",
          chapterImageName: "BOMpic",
          audioFileName: "Helaman2",
          isActiveBookmark: false,
          src: "assets/media/Helaman2.mp3",
        },
        {
          uuid: 166,
          bookID: 11,
          book: "Helaman",
          chapter: 3,
          narrator: "Daniele Benigni",
          narratorImageName: "DanieleBenigni",
          chapterImageName: "BOMpic",
          audioFileName: "Helaman3",
          isActiveBookmark: false,
          src: "assets/media/Helaman3.mp3",
        },
        {
          uuid: 167,
          bookID: 11,
          book: "Helaman",
          chapter: 4,
          narrator: "Lorenzo Botta",
          narratorImageName: "LorenzoBotta",
          chapterImageName: "BOMpic",
          audioFileName: "Helaman4",
          isActiveBookmark: false,
          src: "assets/media/Helaman4.mp3",
        },
        {
          uuid: 168,
          bookID: 11,
          book: "Helaman",
          chapter: 5,
          narrator: "Serena Fiorillo",
          narratorImageName: "SerenaFiorillo",
          chapterImageName: "Helaman5",
          audioFileName: "Helaman5",
          isActiveBookmark: false,
          src: "assets/media/Helaman5.mp3",
        },
        {
          uuid: 169,
          bookID: 11,
          book: "Helaman",
          chapter: 6,
          narrator: "Jessica Caramia",
          narratorImageName: "JessicaCaramia",
          chapterImageName: "BOMpic",
          audioFileName: "Helaman6",
          isActiveBookmark: false,
          src: "assets/media/Helaman6.mp3",
        },
        {
          uuid: 170,
          bookID: 11,
          book: "Helaman",
          chapter: 7,
          narrator: "Marisa Corvasce",
          narratorImageName: "MarisaCorvasce",
          chapterImageName: "BOMpic",
          audioFileName: "Helaman7",
          isActiveBookmark: false,
          src: "assets/media/Helaman7.mp3",
        },
        {
          uuid: 171,
          bookID: 11,
          book: "Helaman",
          chapter: 8,
          narrator: "Enos Corvasce",
          narratorImageName: "EnosCorvasce",
          chapterImageName: "BOMpic",
          audioFileName: "Helaman8",
          isActiveBookmark: false,
          src: "assets/media/Helaman8.mp3",
        },
        {
          uuid: 172,
          bookID: 11,
          book: "Helaman",
          chapter: 9,
          narrator: "Mara Bartolucci",
          narratorImageName: "MaraBartolucci",
          chapterImageName: "BOMpic",
          audioFileName: "Helaman9",
          isActiveBookmark: false,
          src: "assets/media/Helaman9.mp3",
        },
        {
          uuid: 173,
          bookID: 11,
          book: "Helaman",
          chapter: 10,
          narrator: "Angelika Iob",
          narratorImageName: "AngelikaIob",
          chapterImageName: "BOMpic",
          audioFileName: "Helaman10",
          isActiveBookmark: false,
          src: "assets/media/Helaman10.mp3",
        },
        {
          uuid: 174,
          bookID: 11,
          book: "Helaman",
          chapter: 11,
          narrator: "Isabella Persico",
          narratorImageName: "IsabellaPersico",
          chapterImageName: "BOMpic",
          audioFileName: "Helaman11",
          isActiveBookmark: false,
          src: "assets/media/Helaman11.mp3",
        },
        {
          uuid: 175,
          bookID: 11,
          book: "Helaman",
          chapter: 12,
          narrator: "Gabriella Maniero",
          narratorImageName: "GabriellaManiero",
          chapterImageName: "BOMpic",
          audioFileName: "Helaman12",
          isActiveBookmark: false,
          src: "assets/media/Helaman12.mp3",
        },
        {
          uuid: 176,
          bookID: 11,
          book: "Helaman",
          chapter: 13,
          narrator: "Carla Giorgino",
          narratorImageName: "CarlaGiorgino",
          chapterImageName: "Helaman13",
          audioFileName: "Helaman13",
          isActiveBookmark: false,
          src: "assets/media/Helaman13.mp3",
        },
        {
          uuid: 177,
          bookID: 11,
          book: "Helaman",
          chapter: 14,
          narrator: "Ornella Lepore",
          narratorImageName: "OrnellaLepore",
          chapterImageName: "BOMpic",
          audioFileName: "Helaman14",
          isActiveBookmark: false,
          src: "assets/media/Helaman14.mp3",
        },
        {
          uuid: 178,
          bookID: 11,
          book: "Helaman",
          chapter: 15,
          narrator: "Francesco Lepore",
          narratorImageName: "FrancescoLepore",
          chapterImageName: "BOMpic",
          audioFileName: "Helaman15",
          isActiveBookmark: false,
          src: "assets/media/Helaman15.mp3",
        },
        {
          uuid: 179,
          bookID: 11,
          book: "Helaman",
          chapter: 16,
          narrator: "Pina D’Andrea",
          narratorImageName: "PinaDAndrea",
          chapterImageName: "BOMpic",
          audioFileName: "Helaman16",
          isActiveBookmark: false,
          src: "assets/media/Helaman16.mp3",
        },
        {
          uuid: 180,
          bookID: 12,
          book: "3 Nefi",
          chapter: 1,
          narrator: "Daniele Lui",
          narratorImageName: "DanieleLui",
          chapterImageName: "BOMpic",
          audioFileName: "3Nefi1",
          isActiveBookmark: false,
          src: "assets/media/3Nefi1.mp3",
        },
        {
          uuid: 181,
          bookID: 12,
          book: "3 Nefi",
          chapter: 2,
          narrator: "Giuseppe Viglietta",
          narratorImageName: "GiuseppeViglietta",
          chapterImageName: "BOMpic",
          audioFileName: "3Nefi2",
          isActiveBookmark: false,
          src: "assets/media/3Nefi2.mp3",
        },
        {
          uuid: 182,
          bookID: 12,
          book: "3 Nefi",
          chapter: 3,
          narrator: "Antonio Murgia",
          narratorImageName: "AntonioMurgia",
          chapterImageName: "BOMpic",
          audioFileName: "3Nefi3",
          isActiveBookmark: false,
          src: "assets/media/3Nefi3.mp3",
        },
        {
          uuid: 183,
          bookID: 12,
          book: "3 Nefi",
          chapter: 4,
          narrator: "Ester Tonon",
          narratorImageName: "EsterTonon",
          chapterImageName: "BOMpic",
          audioFileName: "3Nefi4",
          isActiveBookmark: false,
          src: "assets/media/3Nefi4.mp3",
        },
        {
          uuid: 184,
          bookID: 12,
          book: "3 Nefi",
          chapter: 5,
          narrator: "Ester Tonon",
          narratorImageName: "EsterTonon",
          chapterImageName: "BOMpic",
          audioFileName: "3Nefi5",
          isActiveBookmark: false,
          src: "assets/media/3Nefi5.mp3",
        },
        {
          uuid: 185,
          bookID: 12,
          book: "3 Nefi",
          chapter: 6,
          narrator: "Tommaso Cardullo",
          narratorImageName: "TommasoCardullo",
          chapterImageName: "BOMpic",
          audioFileName: "3Nefi6",
          isActiveBookmark: false,
          src: "assets/media/3Nefi6.mp3",
        },
        {
          uuid: 186,
          bookID: 12,
          book: "3 Nefi",
          chapter: 7,
          narrator: "Paola Battistini",
          narratorImageName: "PaolaBattistini",
          chapterImageName: "BOMpic",
          audioFileName: "3Nefi7",
          isActiveBookmark: false,
          src: "assets/media/3Nefi7.mp3",
        },
        {
          uuid: 187,
          bookID: 12,
          book: "3 Nefi",
          chapter: 8,
          narrator: "Nicola Scarola",
          narratorImageName: "NicolaScarola",
          chapterImageName: "BOMpic",
          audioFileName: "3Nefi8",
          isActiveBookmark: false,
          src: "assets/media/3Nefi8.mp3",
        },
        {
          uuid: 188,
          bookID: 12,
          book: "3 Nefi",
          chapter: 9,
          narrator: "Carlo Battistini",
          narratorImageName: "CarloBattistini",
          chapterImageName: "BOMpic",
          audioFileName: "3Nefi9",
          isActiveBookmark: false,
          src: "assets/media/3Nefi9.mp3",
        },
        {
          uuid: 189,
          bookID: 12,
          book: "3 Nefi",
          chapter: 10,
          narrator: "Giorgia Castorina",
          narratorImageName: "GiorgiaCastorina",
          chapterImageName: "BOMpic",
          audioFileName: "3Nefi10",
          isActiveBookmark: false,
          src: "assets/media/3Nefi10.mp3",
        },
        {
          uuid: 190,
          bookID: 12,
          book: "3 Nefi",
          chapter: 11,
          narrator: "Antonietta Luvarà",
          narratorImageName: "AntoniettaLuvarà",
          chapterImageName: "3Nephi11",
          audioFileName: "3Nefi11",
          isActiveBookmark: false,
          src: "assets/media/3Nefi11.mp3",
        },
        {
          uuid: 191,
          bookID: 12,
          book: "3 Nefi",
          chapter: 12,
          narrator: "Stefano Pace",
          narratorImageName: "StefanoPace",
          chapterImageName: "3Nephi12",
          audioFileName: "3Nefi12",
          isActiveBookmark: false,
          src: "assets/media/3Nefi12.mp3",
        },
        {
          uuid: 192,
          bookID: 12,
          book: "3 Nefi",
          chapter: 13,
          narrator: "Fernando Curci",
          narratorImageName: "FernandoCurci",
          chapterImageName: "3Nephi13",
          audioFileName: "3Nefi13",
          isActiveBookmark: false,
          src: "assets/media/3Nefi13.mp3",
        },
        {
          uuid: 193,
          bookID: 12,
          book: "3 Nefi",
          chapter: 14,
          narrator: "Francesco Mannino",
          narratorImageName: "FrancescoMannino",
          chapterImageName: "3Nephi14",
          audioFileName: "3Nefi14",
          isActiveBookmark: false,
          src: "assets/media/3Nefi14.mp3",
        },
        {
          uuid: 194,
          bookID: 12,
          book: "3 Nefi",
          chapter: 15,
          narrator: "Massimiliano Carrus",
          narratorImageName: "MassimilianoCarrus",
          chapterImageName: "BOMpic",
          audioFileName: "3Nefi15",
          isActiveBookmark: false,
          src: "assets/media/3Nefi15.mp3",
        },
        {
          uuid: 195,
          bookID: 12,
          book: "3 Nefi",
          chapter: 16,
          narrator: "Mirella Corvasce",
          narratorImageName: "MirellaCorvasce",
          chapterImageName: "BOMpic",
          audioFileName: "3Nefi16",
          isActiveBookmark: false,
          src: "assets/media/3Nefi16.mp3",
        },
        {
          uuid: 196,
          bookID: 12,
          book: "3 Nefi",
          chapter: 17,
          narrator: "Emanuele Carrus",
          narratorImageName: "EmanueleCarrus",
          chapterImageName: "3Nephi17",
          audioFileName: "3Nefi17",
          isActiveBookmark: false,
          src: "assets/media/3Nefi17.mp3",
        },
        {
          uuid: 197,
          bookID: 12,
          book: "3 Nefi",
          chapter: 18,
          narrator: "Alessio Giolitto",
          narratorImageName: "AlessioGiolitto",
          chapterImageName: "BOMpic",
          audioFileName: "3Nefi18",
          isActiveBookmark: false,
          src: "assets/media/3Nefi18.mp3",
        },
        {
          uuid: 198,
          bookID: 12,
          book: "3 Nefi",
          chapter: 19,
          narrator: "Emanuele Carrus",
          narratorImageName: "EmanueleCarrus",
          chapterImageName: "BOMpic",
          audioFileName: "3Nefi19",
          isActiveBookmark: false,
          src: "assets/media/3Nefi19.mp3",
        },
        {
          uuid: 199,
          bookID: 12,
          book: "3 Nefi",
          chapter: 20,
          narrator: "Michol Lo Coco",
          narratorImageName: "MicholLoCoco",
          chapterImageName: "BOMpic",
          audioFileName: "3Nefi20",
          isActiveBookmark: false,
          src: "assets/media/3Nefi20.mp3",
        },
        {
          uuid: 200,
          bookID: 12,
          book: "3 Nefi",
          chapter: 21,
          narrator: "Sergio Giolitto",
          narratorImageName: "SergioGiolitto",
          chapterImageName: "BOMpic",
          audioFileName: "3Nefi21",
          isActiveBookmark: false,
          src: "assets/media/3Nefi21.mp3",
        },
        {
          uuid: 201,
          bookID: 12,
          book: "3 Nefi",
          chapter: 22,
          narrator: "Emanuel Tribaudino",
          narratorImageName: "EmanuelTribaudino",
          chapterImageName: "BOMpic",
          audioFileName: "3Nefi22",
          isActiveBookmark: false,
          src: "assets/media/3Nefi22.mp3",
        },
        {
          uuid: 202,
          bookID: 12,
          book: "3 Nefi",
          chapter: 23,
          narrator: "Marco Marinello",
          narratorImageName: "MarcoMarinello",
          chapterImageName: "BOMpic",
          audioFileName: "3Nefi23",
          isActiveBookmark: false,
          src: "assets/media/3Nefi23.mp3",
        },
        {
          uuid: 203,
          bookID: 12,
          book: "3 Nefi",
          chapter: 24,
          narrator: "Teodora Di Pietro",
          narratorImageName: "TeodoraDiPietro",
          chapterImageName: "BOMpic",
          audioFileName: "3Nefi24",
          isActiveBookmark: false,
          src: "assets/media/3Nefi24.mp3",
        },
        {
          uuid: 204,
          bookID: 12,
          book: "3 Nefi",
          chapter: 25,
          narrator: "Sara Marinello",
          narratorImageName: "SaraMarinello",
          chapterImageName: "BOMpic",
          audioFileName: "3Nefi25",
          isActiveBookmark: false,
          src: "assets/media/3Nefi25.mp3",
        },
        {
          uuid: 205,
          bookID: 12,
          book: "3 Nefi",
          chapter: 26,
          narrator: "Daniele Dicarolo",
          narratorImageName: "DanieleDicarolo",
          chapterImageName: "BOMpic",
          audioFileName: "3Nefi26",
          isActiveBookmark: false,
          src: "assets/media/3Nefi26.mp3",
        },
        {
          uuid: 206,
          bookID: 12,
          book: "3 Nefi",
          chapter: 27,
          narrator: "Emanuele Guidara",
          narratorImageName: "EmanueleGuidara",
          chapterImageName: "BOMpic",
          audioFileName: "3Nefi27",
          isActiveBookmark: false,
          src: "assets/media/3Nefi27.mp3",
        },
        {
          uuid: 207,
          bookID: 12,
          book: "3 Nefi",
          chapter: 28,
          narrator: "Airina Giolitto",
          narratorImageName: "AirinaGiolitto",
          chapterImageName: "3Nephi28",
          audioFileName: "3Nefi28",
          isActiveBookmark: false,
          src: "assets/media/3Nefi28.mp3",
        },
        {
          uuid: 208,
          bookID: 12,
          book: "3 Nefi",
          chapter: 29,
          narrator: "Maria Scarola",
          narratorImageName: "MariaScarola",
          chapterImageName: "BOMpic",
          audioFileName: "3Nefi29",
          isActiveBookmark: false,
          src: "assets/media/3Nefi29.mp3",
        },
        {
          uuid: 209,
          bookID: 12,
          book: "3 Nefi",
          chapter: 30,
          narrator: "Lorenzo Bertone",
          narratorImageName: "LorenzoBertone",
          chapterImageName: "BOMpic",
          audioFileName: "3Nefi30",
          isActiveBookmark: false,
          src: "assets/media/3Nefi30.mp3",
        },
        {
          uuid: 210,
          bookID: 13,
          book: "4 Nefi",
          chapter: 1,
          narrator: "Tommaso Cardullo",
          narratorImageName: "TommasoCardullo",
          chapterImageName: "BOMpic",
          audioFileName: "4Nefi1",
          isActiveBookmark: false,
          src: "assets/media/4Nefi1.mp3",
        },
        {
          uuid: 211,
          bookID: 14,
          book: "Mormon",
          chapter: 1,
          narrator: "Fabio Nannarone",
          narratorImageName: "FabioNannarone",
          chapterImageName: "Mormon1",
          audioFileName: "Mormon1",
          isActiveBookmark: false,
          src: "assets/media/Mormon1.mp3",
        },
        {
          uuid: 212,
          bookID: 14,
          book: "Mormon",
          chapter: 2,
          narrator: "Sara Dini Ciacci",
          narratorImageName: "SaraDiniCiacci",
          chapterImageName: "BOMpic",
          audioFileName: "Mormon2",
          isActiveBookmark: false,
          src: "assets/media/Mormon2.mp3",
        },
        {
          uuid: 213,
          bookID: 14,
          book: "Mormon",
          chapter: 3,
          narrator: "Rebecca Dini Ciacci",
          narratorImageName: "RebeccaDiniCiacci",
          chapterImageName: "BOMpic",
          audioFileName: "Mormon3",
          isActiveBookmark: false,
          src: "assets/media/Mormon3.mp3",
        },
        {
          uuid: 214,
          bookID: 14,
          book: "Mormon",
          chapter: 4,
          narrator: "Filippo Dini Ciacci",
          narratorImageName: "FilippoDiniCiacci",
          chapterImageName: "BOMpic",
          audioFileName: "Mormon4",
          isActiveBookmark: false,
          src: "assets/media/Mormon4.mp3",
        },
        {
          uuid: 215,
          bookID: 14,
          book: "Mormon",
          chapter: 5,
          narrator: "Silvia Guidara",
          narratorImageName: "SilviaGuidara",
          chapterImageName: "Mormon5",
          audioFileName: "Mormon5",
          isActiveBookmark: false,
          src: "assets/media/Mormon5.mp3",
        },
        {
          uuid: 216,
          bookID: 14,
          book: "Mormon",
          chapter: 6,
          narrator: "Daniele Benigni",
          narratorImageName: "DanieleBenigni",
          chapterImageName: "Mormon6",
          audioFileName: "Mormon6",
          isActiveBookmark: false,
          src: "assets/media/Mormon6.mp3",
        },
        {
          uuid: 217,
          bookID: 14,
          book: "Mormon",
          chapter: 7,
          narrator: "Rebecca Bertone",
          narratorImageName: "RebeccaBertone",
          chapterImageName: "BOMpic",
          audioFileName: "Mormon7",
          isActiveBookmark: false,
          src: "assets/media/Mormon7.mp3",
        },
        {
          uuid: 218,
          bookID: 14,
          book: "Mormon",
          chapter: 8,
          narrator: "Giunia Bressan",
          narratorImageName: "GiuniaBressan",
          chapterImageName: "BOMpic",
          audioFileName: "Mormon8",
          isActiveBookmark: false,
          src: "assets/media/Mormon8.mp3",
        },
        {
          uuid: 219,
          bookID: 14,
          book: "Mormon",
          chapter: 9,
          narrator: "Miriam Bressan",
          narratorImageName: "MiriamBressan",
          chapterImageName: "BOMpic",
          audioFileName: "Mormon9",
          isActiveBookmark: false,
          src: "assets/media/Mormon9.mp3",
        },
        {
          uuid: 220,
          bookID: 15,
          book: "Ether",
          chapter: 1,
          narrator: "Biagio Fiorillo",
          narratorImageName: "BiagioFiorillo",
          chapterImageName: "Ether1",
          audioFileName: "Ether1",
          isActiveBookmark: false,
          src: "assets/media/Ether1.mp3",
        },
        {
          uuid: 221,
          bookID: 15,
          book: "Ether",
          chapter: 2,
          narrator: "Adriana Viglietta",
          narratorImageName: "AdrianaViglietta",
          chapterImageName: "Ether2",
          audioFileName: "Ether2",
          isActiveBookmark: false,
          src: "assets/media/Ether2.mp3",
        },
        {
          uuid: 222,
          bookID: 15,
          book: "Ether",
          chapter: 3,
          narrator: "Elisabetta Calabrese",
          narratorImageName: "ElisabettaCalabrese",
          chapterImageName: "Ether3",
          audioFileName: "Ether3",
          isActiveBookmark: false,
          src: "assets/media/Ether3.mp3",
        },
        {
          uuid: 223,
          bookID: 15,
          book: "Ether",
          chapter: 4,
          narrator: "Nico Calabrese",
          narratorImageName: "NicoCalabrese",
          chapterImageName: "BOMpic",
          audioFileName: "Ether4",
          isActiveBookmark: false,
          src: "assets/media/Ether4.mp3",
        },
        {
          uuid: 224,
          bookID: 15,
          book: "Ether",
          chapter: 5,
          narrator: "Andrea Cusumano",
          narratorImageName: "AndreaCusumano",
          chapterImageName: "BOMpic",
          audioFileName: "Ether5",
          isActiveBookmark: false,
          src: "assets/media/Ether5.mp3",
        },
        {
          uuid: 225,
          bookID: 15,
          book: "Ether",
          chapter: 6,
          narrator: "Rosalinda Catania",
          narratorImageName: "RosalindaCatania",
          chapterImageName: "BOMpic",
          audioFileName: "Ether6",
          isActiveBookmark: false,
          src: "assets/media/Ether6.mp3",
        },
        {
          uuid: 226,
          bookID: 15,
          book: "Ether",
          chapter: 7,
          narrator: "Rosalinda Catania",
          narratorImageName: "RosalindaCatania",
          chapterImageName: "BOMpic",
          audioFileName: "Ether7",
          isActiveBookmark: false,
          src: "assets/media/Ether7.mp3",
        },
        {
          uuid: 227,
          bookID: 15,
          book: "Ether",
          chapter: 8,
          narrator: "Daniele Catania",
          narratorImageName: "DanieleCatania",
          chapterImageName: "BOMpic",
          audioFileName: "Ether8",
          isActiveBookmark: false,
          src: "assets/media/Ether8.mp3",
        },
        {
          uuid: 228,
          bookID: 15,
          book: "Ether",
          chapter: 9,
          narrator: "Naomi Torre",
          narratorImageName: "NaomiTorre",
          chapterImageName: "BOMpic",
          audioFileName: "Ether9",
          isActiveBookmark: false,
          src: "assets/media/Ether9.mp3",
        },
        {
          uuid: 229,
          bookID: 15,
          book: "Ether",
          chapter: 10,
          narrator: "Naomi Torre",
          narratorImageName: "NaomiTorre",
          chapterImageName: "BOMpic",
          audioFileName: "Ether10",
          isActiveBookmark: false,
          src: "assets/media/Ether10.mp3",
        },
        {
          uuid: 230,
          bookID: 15,
          book: "Ether",
          chapter: 11,
          narrator: "Veronica Fratta",
          narratorImageName: "VeronicaFratta",
          chapterImageName: "BOMpic",
          audioFileName: "Ether11",
          isActiveBookmark: false,
          src: "assets/media/Ether11.mp3",
        },
        {
          uuid: 231,
          bookID: 15,
          book: "Ether",
          chapter: 12,
          narrator: "Debora Siniscalchi",
          narratorImageName: "DeboraSiniscalchi",
          chapterImageName: "BOMpic",
          audioFileName: "Ether12",
          isActiveBookmark: false,
          src: "assets/media/Ether12.mp3",
        },
        {
          uuid: 232,
          bookID: 15,
          book: "Ether",
          chapter: 13,
          narrator: "Beatrice Dicarolo",
          narratorImageName: "BeatriceDicarolo",
          chapterImageName: "BOMpic",
          audioFileName: "Ether13",
          isActiveBookmark: false,
          src: "assets/media/Ether13.mp3",
        },
        {
          uuid: 233,
          bookID: 15,
          book: "Ether",
          chapter: 14,
          narrator: "Jessica Caramia",
          narratorImageName: "JessicaCaramia",
          chapterImageName: "BOMpic",
          audioFileName: "Ether14",
          isActiveBookmark: false,
          src: "assets/media/Ether14.mp3",
        },
        {
          uuid: 234,
          bookID: 15,
          book: "Ether",
          chapter: 15,
          narrator: "Carla Bertone",
          narratorImageName: "CarlaBertone",
          chapterImageName: "BOMpic",
          audioFileName: "Ether15",
          isActiveBookmark: false,
          src: "assets/media/Ether15.mp3",
        },
        {
          uuid: 235,
          bookID: 16,
          book: "Moroni",
          chapter: 1,
          narrator: "Nicola Giangrosso",
          narratorImageName: "NicolaGiangrosso",
          chapterImageName: "BOMpic",
          audioFileName: "Moroni1",
          isActiveBookmark: false,
          src: "assets/media/Moroni1.mp3",
        },
        {
          uuid: 236,
          bookID: 16,
          book: "Moroni",
          chapter: 2,
          narrator: "Carmela Gibilisco",
          narratorImageName: "CarmelaGibilisco",
          chapterImageName: "BOMpic",
          audioFileName: "Moroni2",
          isActiveBookmark: false,
          src: "assets/media/Moroni2.mp3",
        },
        {
          uuid: 237,
          bookID: 16,
          book: "Moroni",
          chapter: 3,
          narrator: "Enoc Pulvirenti",
          narratorImageName: "EnocPulvirenti",
          chapterImageName: "BOMpic",
          audioFileName: "Moroni3",
          isActiveBookmark: false,
          src: "assets/media/Moroni3.mp3",
        },
        {
          uuid: 238,
          bookID: 16,
          book: "Moroni",
          chapter: 4,
          narrator: "Marco Diodato",
          narratorImageName: "MarcoDiodato",
          chapterImageName: "BOMpic",
          audioFileName: "Moroni4",
          isActiveBookmark: false,
          src: "assets/media/Moroni4.mp3",
        },
        {
          uuid: 239,
          bookID: 16,
          book: "Moroni",
          chapter: 5,
          narrator: "Giorgio Cascone",
          narratorImageName: "GiorgioCascone",
          chapterImageName: "BOMpic",
          audioFileName: "Moroni5",
          isActiveBookmark: false,
          src: "assets/media/Moroni5.mp3",
        },
        {
          uuid: 240,
          bookID: 16,
          book: "Moroni",
          chapter: 6,
          narrator: "Elisabetta Angioni",
          narratorImageName: "ElisabettaAngioni",
          chapterImageName: "BOMpic",
          audioFileName: "Moroni6",
          isActiveBookmark: false,
          src: "assets/media/Moroni6.mp3",
        },
        {
          uuid: 241,
          bookID: 16,
          book: "Moroni",
          chapter: 7,
          narrator: "Giuseppe Ariante",
          narratorImageName: "GiuseppeAriante",
          chapterImageName: "BOMpic",
          audioFileName: "Moroni7",
          isActiveBookmark: false,
          src: "assets/media/Moroni7.mp3",
        },
        {
          uuid: 242,
          bookID: 16,
          book: "Moroni",
          chapter: 8,
          narrator: "Riccardo Vanoli",
          narratorImageName: "RiccardoVanoli",
          chapterImageName: "BOMpic",
          audioFileName: "Moroni8",
          isActiveBookmark: false,
          src: "assets/media/Moroni8.mp3",
        },
        {
          uuid: 243,
          bookID: 16,
          book: "Moroni",
          chapter: 9,
          narrator: "Franca Wei",
          narratorImageName: "FrancaWei",
          chapterImageName: "BOMpic",
          audioFileName: "Moroni9",
          isActiveBookmark: false,
          src: "assets/media/Moroni9.mp3",
        },
        {
          uuid: 244,
          bookID: 16,
          book: "Moroni",
          chapter: 10,
          narrator: "Vincenzo Conforte",
          narratorImageName: "VincenzoConforte",
          chapterImageName: "Moroni10",
          audioFileName: "Moroni10",
          isActiveBookmark: false,
          src: "assets/media/Moroni10.mp3",
        },
      ],
    };
  },
  beforeUpdate() {
    this.currentImage = "./assets/photos/" + this.selectedReader.narratorImageName + ".jpg";
    this.index = this.selectedReader.uuid - 1; //reset the index
  },
  mounted() {
    this.determineUserAndReader();
    this.currentImage =
      "./assets/photos/" + this.selectedReader.narratorImageName + ".jpg";
    this.index = this.selectedReader.uuid - 1;
    this.audio.src = this.selectedReader.src;
    this.audio.volume = this.volume / 100;
    this.progressBar = document.querySelector("#progressBar");
    this.progressBar.value = 0;
    this.initProgress();
  },
  methods: {
    determineUserAndReader() {
      const user1 = usePage().props.value.auth.user;
      const theReader = this.readers.filter(
        (reader) => reader.uuid === user1.uuid
      );
      this.updateSelectedReader(theReader[0]);
    },
    initProgress() {
      this.audio.addEventListener("loadedmetadata", () => {
        this.currentDuration = this.audio.duration;
        let secs = `${parseInt(`${this.currentDuration % 60}`, 10)}`.padStart(
          2,
          "0"
        );
        let mins = parseInt(`${(this.currentDuration / 60) % 60}`, 10);
        this.currentDurationTxt = `${mins}:${secs}`;
        this.progressBar.max = this.currentDuration;
      });
      this.audio.addEventListener("timeupdate", () => {
        this.updateProgress(this.audio.currentTime);
      });
    },
    updateProgress(time) {
      this.progressBar.value = time;
      let secs = `${parseInt(`${time % 60}`, 10)}`.padStart(2, "0");
      let mins = parseInt(`${(time / 60) % 60}`, 10);
      this.currentTimeTxt = `${mins}:${secs}`;
    },
    updateVolume() {
      this.audio.volume = this.volume / 100;
      this.isMuted = false;
      if (this.volume >= 100) {
        this.isMaxed = true;
        this.isMuted = false;
      } else if (this.volume <= 0) {
        this.isMaxed = false;
        this.isMuted = true;
      }
    },
    mute() {
      this.isMuted = true;
      this.isMaxed = false;
      this.volume = 0;
      this.audio.volume = 0;
    },
    max() {
      this.isMaxed = true;
      this.isMuted = false;
      this.volume = 100;
      this.audio.volume = this.volume / 100;
    },
    play(reader) {
      // ????????
      // If the current image has changed, stop playing
      // => Trying to stop play when menu has selected a new reader

      if (typeof reader.src != "undefined") {
        this.audio.src = this.selectedReader.src;
      }
      this.audio.src = this.selectedReader.src;
      this.index = this.selectedReader.uuid - 1;
      this.audio.play();
      this.isPlaying = true;
    },
    pause() {
      // console.log("pause");
      this.audio.pause();
      this.isPlaying = false;
    },
    next() {
      this.index++; //index is the location in readers array. It is equal to uuid-1.
      this.index > this.readers.length - 1 ? (this.index = 5) : this.index; //returns to 1 Nefi 1
      this.updateSelectedReader(this.readers[this.index]);
      this.play(this.selectedReader.src);
      this.currentImage =
        "assets/photos/" + this.selectedReader.narratorImageName + ".jpg";
      // console.log("The current selected reader uuid is:",this.selectedReader.uuid)
      const user1 = usePage().props.value.auth.user;
      axios.put(
        route("reader", { uuid: this.selectedReader.uuid, user_id: user1.id })
      );
    },
    prev() {
      this.index--;
      this.index < 0 ? (this.index = 5) : this.index; //returns to 1 Nefi 1
      this.updateSelectedReader(this.readers[this.index]);
      this.play(this.selectedReader.src);
      this.currentImage =
        "assets/photos/" + this.selectedReader.narratorImageName + ".jpg";
      const user1 = usePage().props.value.auth.user;
      axios.put(
        route("reader", { uuid: this.selectedReader.uuid, user_id: user1.id })
      );
    },
    updateSelectedReader(reader) {
      //not sure why this is necessary, as this.selectedReader = reader should work, but it does not.
      this.selectedReader.uuid = reader.uuid;
      this.selectedReader.bookID = reader.bookID;
      this.selectedReader.book = reader.book;
      this.selectedReader.chapter = reader.chapter;
      this.selectedReader.narrator = reader.narrator;
      this.selectedReader.narratorImageName = reader.narratorImageName;
      this.selectedReader.chapterImageName = reader.chapterImageName;
      this.selectedReader.audioFileName = reader.audioFileName;
      this.selectedReader.isActiveBookmark = reader.isActiveBookmark;
      this.selectedReader.src = reader.src;
    },
  },
};
</script>